const fs = require('fs');
const path = require('path');
const jsonSass = require('json-sass');

const src = fs.createReadStream(__dirname + '/../design-tokens.json');
const dest = fs.createWriteStream(`${path.join(__dirname, '../src')}/_design-tokens.scss`);

const documentMeta = `
/**
 * This is a generated file. Do not edit this file directly.
 * Run '$ yarn run build-design-tokens' to generate new SASS variables
 */
`;

dest.write(documentMeta + '\n');

src.pipe(jsonSass({
  prefix: '$theme: ',
  suffix: '\n'
})).pipe(dest);
